apiVersion: v1
entries:
  node-feature-discovery:
  - apiVersion: v2
    appVersion: v0.18.3
    created: "2026-06-11T02:40:19.039539199Z"
    description: 'Detects hardware features available on each node in a Kubernetes
      cluster, and advertises those features using node labels. '
    digest: 9f53ea8499a9d81d3d028c0141f35f54f38d3eb7f86b4fee30618f475b89e77a
    home: https://github.com/thxcode/node-feature-discovery
    icon: https://kubernetes-sigs.github.io/node-feature-discovery/v0.18/assets/images/nfd/favicon.svg
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/thxcode/node-feature-discovery
    type: application
    urls:
    - https://thxCode.github.io/node-feature-discovery/charts/node-feature-discovery-0.18.3.tgz
    version: 0.18.3
  - apiVersion: v2
    appVersion: v0.18.3
    created: "2026-06-11T01:58:20.301413667Z"
    description: 'Detects hardware features available on each node in a Kubernetes
      cluster, and advertises those features using node labels. '
    digest: 7799dc306a6b273361ba93af1d1a8c814bd800180807bb3a34a33f2c2408545c
    home: https://github.com/thxcode/node-feature-discovery
    icon: https://kubernetes-sigs.github.io/node-feature-discovery/v0.18/assets/images/nfd/favicon.svg
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/thxcode/node-feature-discovery
    type: application
    urls:
    - https://thxCode.github.io/node-feature-discovery/charts/node-feature-discovery-0.2.1.tgz
    version: 0.2.1
generated: "2026-06-11T02:40:19.037188135Z"
