name: ci

permissions:
  actions: read
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - "main"
      - "v*-dev"
    tags:
      - "v*"
    paths-ignore:
      - "!.github/workflows/ci.yml"
      - "deploy/**"
      - "test/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.webp"
  pull_request:
    branches:
      - "main"
      - "v*-dev"
    paths-ignore:
      - "!.github/workflows/ci.yml"
      - "deploy/**"
      - "test/**"
      - "**.md"
      - "**.mdx"
      - "**.png"
      - "**.jpg"
      - "**.jpeg"
      - "**.gif"
      - "**.webp"

env:
  INPUT_PLATFORM: "linux/amd64,linux/arm64"
  INPUT_PASSWORD: ${{ secrets.CI_DOCKERHUB_PASSWORD }}
  INPUT_REPOSITORY: node-feature-discovery

jobs:
  pack:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Env
        env:
          INPUT_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          INPUT_REPOSITORY_OWNER=$(echo "${INPUT_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "INPUT_NAMESPACE=${INPUT_REPOSITORY_OWNER}" >> $GITHUB_ENV
          echo "INPUT_USERNAME=${INPUT_REPOSITORY_OWNER}" >> $GITHUB_ENV
          echo "DEBUG: INPUT_NAMESPACE=${INPUT_NAMESPACE}"
          echo "DEBUG: INPUT_USERNAME=${INPUT_USERNAME}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64"
      - name: Setup BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
            env.BUILDKIT_STEP_LOG_MAX_SIZE=-1
            env.BUILDKIT_STEP_LOG_MAX_SPEED=-1
          buildkitd-flags: |
            --allow-insecure-entitlement=network.host
            --allow-insecure-entitlement=security.insecure
            --oci-worker-net=host
            --oci-worker-gc-keepstorage=204800
      - name: Login DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.INPUT_USERNAME }}
          password: ${{ env.INPUT_PASSWORD }}
      - name: Get Metadata
        id: metadata
        uses: docker/metadata-action@v5
        # NB(thxCode): Don't forget to update the Get Metadata step in the manifest job if you change the tags format here.
        with:
          images: "${{ env.INPUT_NAMESPACE }}/${{ env.INPUT_REPOSITORY }}"
          tags: |
            type=ref,event=pr
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=dev-,enable=${{ github.ref == 'refs/heads/main' }}
            type=ref,event=branch,enable=${{ contains(github.ref, 'refs/heads/v') && endsWith(github.ref, '-dev') }}
            type=sha,prefix={{branch}}-,enable=${{ contains(github.ref, 'refs/heads/v') && endsWith(github.ref, '-dev') }}
            type=pep440,pattern={{raw}}
            type=pep440,pattern=v{{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
          flavor: |
            latest=false
      - name: Get Build Cache Ref
        run: |
          #
          # Use different cache ref for different branches.
          #
          # Examples:
          # CACHE_FROM_REF
          #   - vX.Y.Z                 -> "${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${VERSION|DEFAULT_BRANCH}"
          #   - PR/PUSH to branch      -> "${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${BRANCH|DEFUALT_BRANCH}"
          # CACHE_TO_REF
          #   - vX.Y.Z                 -> "${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${VERSION}"
          #   - PUSH to branch         -> "${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${BRANCH}"
          #
          # Stories:
          # CACHE_FROM_REF
          #   - Release tag v0.7.0rc1      -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7, if not found, fallback to ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - Release tag v0.7.0         -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7
          #   - PR to "main" branch        -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - PR to "v0.7-dev" branch    -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7, if not found, fallback to ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - Push to "main" branch      -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - Push to "v0.7-dev" branch  -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7, if not found, fallback to ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          # CACHE_TO_REF
          #   - Release tag v0.7.0rc1      -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7
          #   - Release tag v0.7.0         -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7
          #   - PR to "main" branch        -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - PR to "v0.7-dev" branch    -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7
          #   - Push to "main" branch      -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-dev
          #   - Push to "v0.7-dev" branch  -> ${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-v0.7
          #
          DEFAULT_BRANCH="dev"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            REF="${GITHUB_REF#refs/tags/}"
            IFS="." read -r VERSION_MAJOR VERSION_MINOR VERSION_PATCH <<< "${REF}"
            VERSION="${VERSION_MAJOR}.${VERSION_MINOR}"
            CACHE_FROM_REF="${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${VERSION}"
            CACHE_TO_REF="${CACHE_FROM_REF}"
          else
            REF="${GITHUB_BASE_REF:-${GITHUB_REF}}"
            BRANCH="${REF#refs/heads/}"
            BRANCH="${BRANCH%-dev}"
            CACHE_FROM_REF="${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${BRANCH}"
            CACHE_TO_REF="${CACHE_FROM_REF}"
          fi
          if ! docker manifest inspect "${CACHE_FROM_REF}" >/dev/null 2>&1; then
            CACHE_FROM_REF="${INPUT_NAMESPACE}/build-cache:${INPUT_REPOSITORY}-${DEFAULT_BRANCH}"
          fi
          echo "CACHE_FROM_REF=${CACHE_FROM_REF}" >> $GITHUB_ENV
          echo "CACHE_TO_REF=${CACHE_TO_REF}" >> $GITHUB_ENV
          echo "DEBUG: GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "DEBUG: GITHUB_REF=${GITHUB_REF}"
          echo "DEBUG: CACHE_FROM_REF=${CACHE_FROM_REF}"
          echo "DEBUG: CACHE_TO_REF=${CACHE_TO_REF}"
      - name: Package
        uses: docker/build-push-action@v6
        with:
          allow: |
            network.host
            security.insecure
          ulimit: |
            nofile=65536:65536
          shm-size: "16G"
          provenance: false
          sbom: false
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ github.workspace }}/Dockerfile
          context: ${{ github.workspace }}
          platforms: ${{ env.INPUT_PLATFORM }}
          build-args:
            BUILDER_IMAGE=golang:1.25.3-trixie
          target: minimal
          tags: |
            ${{ steps.metadata.outputs.tags }}
          labels: |
            ${{ steps.metadata.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ env.CACHE_FROM_REF }}
          cache-to: |
            ${{ github.event_name != 'pull_request' && format('type=registry,mode=max,compression=gzip,ref={0},ignore-error=true', env.CACHE_TO_REF) || '' }}
